### ISSUE TITLE
Exception: Invalid requirement, parse error at "'.'"

### ISSUE THREAD

**Issue by mmphego** [Afonasev/flake8-awesome#4]
### Describe the bug
See exception below.

```bash
$ flake8 integration_tests/tests/observation_control/astrokat_unittests.py

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3103, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'.'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmphego/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/home/mmphego/.local/lib/python3.8/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.8/dist-packages/flake8_requirements/checker.py", line 498, in run
    mods_3rd_party = self.get_mods_3rd_party()
  File "/usr/local/lib/python3.8/dist-packages/flake8_requirements/checker.py", line 40, in w
    memoize.mem[f] = f(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flake8_requirements/checker.py", line 477, in get_mods_3rd_party
    for requirement in self.get_mods_3rd_party_requirements():
  File "/usr/local/lib/python3.8/dist-packages/flake8_requirements/checker.py", line 471, in get_mods_3rd_party_requirements
    return self.get_requirements_txt()
  File "/usr/local/lib/python3.8/dist-packages/flake8_requirements/checker.py", line 40, in w
    memoize.mem[f] = f(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flake8_requirements/checker.py", line 416, in get_requirements_txt
    return tuple(parse_requirements(cls.resolve_requirement(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3096, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3105, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'.'"

```
### Steps to reproduce the behaviour

1. Do this 'pip install -U flake8 flake8-awesome'
2. View the output, *see above*

#### Versions

```bash 
$ flake8 --version

3.7.9 (flake8-annotations-complexity: 0.0.4, flake8-bandit: 2.1.2, flake8-breakpoint: 1.1.0, flake8-bugbear: 20.1.4, flake8-comprehensions: 3.2.3, flake8-eradicate: 0.4.0, flake8-expression-complexity: 0.0.7, flake8-if-expr: 1.0.4, flake8-print: 3.1.4, flake8-pytest: 1.3, flake8-pytest-style: 1.2.1, flake8-requirements: 1.3.2, flake8-return: 1.1.1, flake8_builtins: 1.5.2, flake8_isort: 3.0.0, logging-format: 0.6.0, mccabe: 0.6.1, naming: 0.11.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.2 on Linux
```

```bash
$ pip show flake8-awesome

Name: flake8-awesome
Version: 1.3.0
Summary: Flake8 awesome plugins pack
Home-page: https://pypi.org/project/flake8-awesome
Author: Afonasev Evgeniy
Author-email: ea.afonasev@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: flake8-breakpoint, flake8-builtins, flake8-comprehensions, flake8-return, flake8-pytest-style, flake8-eradicate, flake8-annotations-complexity, flake8-expression-complexity, flake8-pytest, flake8-requirements, pep8-naming, flake8-print, flake8-bugbear, flake8-bandit, flake8-isort, flake8, flake8-if-expr, flake8-logging-format
Required-by: 
```

```bash
python --version

Python 3.8.2
```

```bash
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by afonasev** [comment]
The flake8-requirements plugin can not parse your requirements.txt file. Can you show requirements.txt body? The flake8-requirements plugin was not written by me. I will remove it from flake8-awesome, If it has unsolvable problems.

**Comment by mmphego** [comment]
> The flake8-requirements plugin can not parse your requirements.txt file. Can you show requirements.txt body? The flake8-requirements plugin was not written by me. I will remove it from flake8-awesome, If it has unsolvable problems.

:laughing: I do not have a `requirements.txt` file in the parent dir.
Removing it would be awesome thanks, I suppose whoever needs it will just pip install it anyway.
Thanks
